- name: "join :: #Jameson Abade# criando o comando join kubeadm"
  become: true
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: "join :: definindo o comando join"
  ansible.builtin.set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"