- name: "install :: #Jameson Abade# atualizando listas de pacotes"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: #Jameson Abade# instalando os pacotes Kubernetes"
  become: true
  ansible.builtin.apt:
    pkg:
      - kubectl
    force_apt_get: true

- name: "config :: #Jameson Abade# Fixando o pacote kubeadm na versão atual"
  become: true
  ansible.builtin.dpkg_selections:
    name: 'kubectl'
    selection: hold