- name: "config :: #Jameson Abade# A porta TCP 6443 do nรณ master pode ser acessada pelo worker"
  become: true
  ansible.builtin.wait_for: "host={{ hostvars[groups['masters'][0]].ansible_host }} port=6443 timeout=1"

- name: "config :: #Jameson Abade# unindo os control plane2 ao cluster"
  become: true
  ansible.builtin.shell: "{{ hostvars[groups['masters'][0]].join_command }} \
                         --control-plane \
                         --certificate-key {{ hostvars[groups['masters'][0]].key_command }} "