- name: "config :: #Jameson Abade# Criando um diret처rio se ele n찾o existir"
  become: true
  ansible.builtin.file:
    path: /mnt/kubernetes-volumes/data
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: "config :: #Jameson Abade# limitando o compartilhamento ao CIDR usado pelos n처s do cluster Kubernetes para acesso externo."
  become: true
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
    - '/mnt/kubernetes-volumes {{ nfs.whitelist_ips }}(rw,sync,no_subtree_check,insecure,no_root_squash)' 

- name: "config :: #Jameson Abade# reinicando nfs-kernel-server.service"
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: nfs-kernel-server.service

- name: "config :: atualizando e exportando lista de diret처rios expostados para o compartilhamento"
  become: true
  command: exportfs -rav