- name: "config :: #Jameson Abade# configurando Cgroup"
  become: true
  ansible.builtin.shell: |
    sudo mkdir -p /etc/containerd
    sudo containerd config default | sudo tee /etc/containerd/config.toml
    sudo sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
  
- name: "config :: #Jameson Abade# Reiniciando e habilitando containerd"
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes
    