- name: "install :: #Jameson Abade# Instalando ca-certificates e curl"
  become: true
  ansible.builtin.apt:
    name: 
      - ca-certificates
      - curl
    state: present

- name: "install :: #Jameson Abade# Adicionando a chave do containerd"
  become: true
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "install :: #Jameson Abade# Adicionando repositório Docker ao sources.list"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker
    
- name: "install :: #Jameson Abade# Atualizar lista de repositórios Apt"
  become: true
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: "install :: #Jameson Abade#  Instalando os pacotes do containerd"
  become: true
  ansible.builtin.apt:
    pkg:
      - containerd.io
    force_apt_get: true
